apiVersion: v1
kind: Namespace
metadata:
  name: ml-lab

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-api
  namespace: ml-lab
spec:
  replicas: 1

  selector:
    matchLabels:
      app: qwen-api

  template:
    metadata:
      labels:
        app: qwen-api

    spec:
      containers:
        - name: qwen-api
          image: qwen-api:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: qwen-api
  namespace: ml-lab
spec:
  type: ClusterIP

  selector:
    app: qwen-api

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP